--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-05-13 16:17:44 EDT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 227 (class 1259 OID 24661)
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetRoleClaims" OWNER TO admin;

--
-- TOC entry 226 (class 1259 OID 24660)
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 24646)
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE public."AspNetRoles" OWNER TO admin;

--
-- TOC entry 229 (class 1259 OID 24674)
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE public."AspNetUserClaims" OWNER TO admin;

--
-- TOC entry 228 (class 1259 OID 24673)
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 24686)
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE public."AspNetUserLogins" OWNER TO admin;

--
-- TOC entry 231 (class 1259 OID 24698)
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE public."AspNetUserRoles" OWNER TO admin;

--
-- TOC entry 232 (class 1259 OID 24715)
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text
);


ALTER TABLE public."AspNetUserTokens" OWNER TO admin;

--
-- TOC entry 225 (class 1259 OID 24653)
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE public."AspNetUsers" OWNER TO admin;

--
-- TOC entry 223 (class 1259 OID 24633)
-- Name: ProjectComments; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."ProjectComments" (
    "ProjectCommentId" integer NOT NULL,
    "Content" character varying(500),
    "DatePosted" timestamp with time zone NOT NULL,
    "ProjectId" integer NOT NULL
);


ALTER TABLE public."ProjectComments" OWNER TO admin;

--
-- TOC entry 222 (class 1259 OID 24632)
-- Name: ProjectComments_ProjectCommentId_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."ProjectComments" ALTER COLUMN "ProjectCommentId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProjectComments_ProjectCommentId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 24592)
-- Name: ProjectTasks; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."ProjectTasks" (
    "ProjectTaskId" integer NOT NULL,
    "Title" character varying(100) NOT NULL,
    "Description" character varying(500) DEFAULT ''::character varying NOT NULL,
    "ProjectId" integer NOT NULL
);


ALTER TABLE public."ProjectTasks" OWNER TO admin;

--
-- TOC entry 220 (class 1259 OID 24591)
-- Name: ProjectTasks_ProjectTaskId_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."ProjectTasks" ALTER COLUMN "ProjectTaskId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProjectTasks_ProjectTaskId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 24584)
-- Name: Projects; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."Projects" (
    "ProjectId" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "Status" text
);


ALTER TABLE public."Projects" OWNER TO admin;

--
-- TOC entry 218 (class 1259 OID 24583)
-- Name: Projects_ProjectId_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."Projects" ALTER COLUMN "ProjectId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Projects_ProjectId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 24578)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO admin;

--
-- TOC entry 3514 (class 2606 OID 24667)
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3506 (class 2606 OID 24652)
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- TOC entry 3517 (class 2606 OID 24680)
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- TOC entry 3520 (class 2606 OID 24692)
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- TOC entry 3523 (class 2606 OID 24704)
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- TOC entry 3525 (class 2606 OID 24721)
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- TOC entry 3510 (class 2606 OID 24659)
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- TOC entry 3504 (class 2606 OID 24639)
-- Name: ProjectComments PK_ProjectComments; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."ProjectComments"
    ADD CONSTRAINT "PK_ProjectComments" PRIMARY KEY ("ProjectCommentId");


--
-- TOC entry 3501 (class 2606 OID 24598)
-- Name: ProjectTasks PK_ProjectTasks; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."ProjectTasks"
    ADD CONSTRAINT "PK_ProjectTasks" PRIMARY KEY ("ProjectTaskId");


--
-- TOC entry 3498 (class 2606 OID 24590)
-- Name: Projects PK_Projects; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."Projects"
    ADD CONSTRAINT "PK_Projects" PRIMARY KEY ("ProjectId");


--
-- TOC entry 3496 (class 2606 OID 24582)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3508 (class 1259 OID 24732)
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- TOC entry 3512 (class 1259 OID 24727)
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- TOC entry 3515 (class 1259 OID 24729)
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- TOC entry 3518 (class 1259 OID 24730)
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- TOC entry 3521 (class 1259 OID 24731)
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- TOC entry 3502 (class 1259 OID 24645)
-- Name: IX_ProjectComments_ProjectId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_ProjectComments_ProjectId" ON public."ProjectComments" USING btree ("ProjectId");


--
-- TOC entry 3499 (class 1259 OID 24604)
-- Name: IX_ProjectTasks_ProjectId; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX "IX_ProjectTasks_ProjectId" ON public."ProjectTasks" USING btree ("ProjectId");


--
-- TOC entry 3507 (class 1259 OID 24728)
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- TOC entry 3511 (class 1259 OID 24733)
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- TOC entry 3528 (class 2606 OID 24668)
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3529 (class 2606 OID 24681)
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3530 (class 2606 OID 24693)
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3531 (class 2606 OID 24705)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- TOC entry 3532 (class 2606 OID 24710)
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3533 (class 2606 OID 24722)
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- TOC entry 3527 (class 2606 OID 24640)
-- Name: ProjectComments FK_ProjectComments_Projects_ProjectId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."ProjectComments"
    ADD CONSTRAINT "FK_ProjectComments_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES public."Projects"("ProjectId") ON DELETE CASCADE;


--
-- TOC entry 3526 (class 2606 OID 24599)
-- Name: ProjectTasks FK_ProjectTasks_Projects_ProjectId; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."ProjectTasks"
    ADD CONSTRAINT "FK_ProjectTasks_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES public."Projects"("ProjectId") ON DELETE CASCADE;


-- Completed on 2025-05-13 16:17:45 EDT

--
-- PostgreSQL database dump complete
--

